plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        url "https://cursemaven.com"
    }
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.ithundxr.dev/snapshots" }
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")

    // Mega Cells
    implementation "curse.maven:mega-cells-622112:7952621"
    // Ae Infinity Booster
    implementation "curse.maven:aeinfinitybooster-559313:7402808"
    // Ae2 Import Export
    implementation "curse.maven:ae2-import-export-card-982512:8033654"
    // ExtendedAE
    implementation "curse.maven:ex-pattern-provider-892005:8025439"
    // AdvancedAE
    implementation "curse.maven:advancedae-1084104:7849217"
    // AE2
    implementation "curse.maven:applied-energistics-2-223794:7027323"
    // Ae Additions
    implementation "curse.maven:ae-additions-extra-cells-2-fork-493962:7661276"
    // Me Requester
    implementation "curse.maven:merequester-688367:7844592"
    // App Mek
    implementation "curse.maven:applied-mekanistics-574300:7096962"
    // Create Applied Kinetics
    implementation "curse.maven:create-applied-kinetics-867328:7220195"
    // AppliedE
    implementation "curse.maven:appliede-1009940:6500056"
    // Applied Energistics 2 Wireless Terminals
    implementation "curse.maven:applied-energistics-2-wireless-terminals-459929:8048692"
    // Bigger Ae2
    implementation "curse.maven:bigger-ae2-1013772:6587078"
    // Ars Energistique
    implementation "curse.maven:ars-energistique-905641:6203425"
    // Applied Flux
    implementation "curse.maven:applied-flux-965012:7429565"
    // Better P2P
    implementation "curse.maven:betterp2p-538092:7140376"
    // Ae2 Mega Things
    implementation "curse.maven:ae2-mega-things-1150075:6203833"

    implementation "curse.maven:glodium-957920:5821676"
    implementation "curse.maven:geckolib-388172:7707149"
    implementation "curse.maven:guideme-1173950:7127444"
    implementation "curse.maven:pipez-443900:5757713"
    implementation "curse.maven:mekanism-268560:7132168"
    implementation "curse.maven:mekanism-generators-268566:7132171"
    implementation "curse.maven:mekanism-tools-268567:7132172"
    implementation "curse.maven:kotlin-for-forge-351264:7471280"
    implementation "curse.maven:ars-nouveau-401955:8152094"
    implementation "curse.maven:curios-309927:6529130"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}